### PR TITLE
Add title screen and update art assets

### PR DESCRIPTION
**Pull request by loteque**

### CODE REVIEW

**Comment by jonathandavidlewis** [comment]
@loteque Nice! Is it possible to include a clip or no? I ask for the sake of keeping that a regular practice. I recall you had some issue with obs.

What is the change with the die texture? I could't see a difference visually, so just making sure there was a real change.

**Comment by jonathandavidlewis** [comment]
This is non-blocking, but curious about your thoughts. What do you think of using computer chips instead of dice? Or using computer chips somehow? I thought the computer chip look would help sell the idea that we are in some kind of machine quickly. 

image

image

image

image

**Comment by jonathandavidlewis** [comment]
I just realized you had images in discord. If you have any trouble with obs, screenshots would still be nice, so I'm adding those here.

image

image

image

**Comment by loteque** [comment]
I really like the computer chip idea. I'll make that change and post some screens before we merge this. Haven't fixed OBS, but I'll make sure to attach screens for you.

**Comment by jonathandavidlewis** [comment]
@loteque Sweet! Sounds like a plan!

**Comment by loteque** [comment]
Can we merge this? I need to move on to doing the start select screen. If I have time I can create and add the new assets later...

**Comment by jonathandavidlewis** [comment]
@loteque This part: "What is the change with the die texture? I could't see a difference visually, so just making sure there was a real change."

**Comment by loteque** [comment]
The die texture is a light yellow green color, if your monitor's gamma is up it may not read.

**Comment by jonathandavidlewis** [comment]
Thanks, merging. Just wanted to make sure it was a real edit. I'll check my gamma.

**Pull request merged**
